import random
from pathlib import Path
from string import Template
from typing import Union

STARTUP_SCRIPT_TEMPLATE = Template(
    """
# THIS FILE IS AUTOMATICALLY GENERATED BY zipapp-creator
# DO NOT MODIFY IT MANUALLY!!!
import shutil
import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
from zipfile import ZipFile


def main():
    with TemporaryDirectory() as temp_dir:
        temp_dir = Path(temp_dir)
        #print(f"Extracting files to {temp_dir.absolute()}")
        self_path = sys.argv[0]
        with ZipFile(self_path, "r") as zip_file:
            zip_file.extractall(temp_dir)
        sys.path.append(temp_dir.absolute().as_posix())
        main_script = "${main_script}"
        main_script = (temp_dir / main_script).absolute().as_posix()
        try:
            cmd = [sys.executable, main_script]
            subprocess.run(cmd, check=True)
        except BaseException as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(-1)
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)


# END OF GENERATED CODE
"""
)


def create_startup_script(
    target_dir: Union[str, Path], main_script: Union[str, Path]
) -> Path:
    target_dir = Path(target_dir)
    main_script = target_dir / main_script
    startup_script_name = "__startup__.py"
    if (target_dir / startup_script_name).exists():
        startup_script_name = f"__startup{hex(random.randint(999, 999999))[2:]}__.py"
    startup_script = target_dir / startup_script_name
    main_script_rel = main_script.relative_to(target_dir).as_posix()
    startup_script_content = STARTUP_SCRIPT_TEMPLATE.substitute(
        main_script=main_script_rel
    )
    startup_script.write_text(startup_script_content, encoding="utf-8")
    return startup_script
